# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

<% pool_size = ENV.fetch('RAILS_MAX_THREADS') { 5 } * ENV.fetch('RAILS_MAX_ASYNC_QUERIES') { 5 } %>

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= pool_size %>
  database: <%= ENV.fetch("DB_NAME", "") %>
  username: <%= ENV.fetch("DB_USER", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>
  reconnect: <%= ENV.fetch("DB_RECONNECT", false) %>

development:
  <<: *default

production:
  <<: *default
  ssl_mode: verify_identity
