name: Fly Deploy
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

env:
  PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
  PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
  PLANETSCALE_ORG: bmorrison-ps

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install the latest pscale CLI from GitHub releases
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: planetscale/cli
      - name: Get Deploy Requests
        if: github.event.pull_request.merged == true
        run: |
          pscale deploy-request list tweeter --org ${{ env.PLANETSCALE_ORG }} -f json > dr_output.txt
          deploy_request_number=$(jq --arg branch ${{ github.head_ref }} '.[] | select(.state == "open" and .branch == $branch) | .number' dr_output.txt)
          echo "DEPLOY_REQUEST_NUMBER=$deploy_request_number" >> $GITHUB_ENV

      - name: Deploy schema migrations
        if: ${{ env.DEPLOY_REQUEST_NUMBER }}
        run: |
          pscale deploy-request deploy tweeter ${{ env.DEPLOY_REQUEST_NUMBER }} --wait --org ${{ env.PLANETSCALE_ORG }}
      - name: Setup fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly
        run: flyctl deploy --remote-only --strategy immediate
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
